name: blog

on:
  push:
    branches: [main]
  # New posts published every monday at 12, run schedule to update at 14 o'clock.
  schedule:
    - cron: "0 14 * * 1"

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.6.3
        with:
          feed_list: "https://onwebfocus.com/api/feed/rss.xml"
          max_post_count: 7
