name: blog

on:
  push:
    branches: [main]
  # Run schedule to update every Monday at 15 o'clock (Zurich time).
  schedule:
    - cron: "0 14 * * 1"

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://onwebfocus.com/api/feed/rss.xml"
          max_post_count: 7
